debug: true
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  profiles:
    active: local
  datasource:
    initialization-mode: always
    continue-on-error: true
    sql-script-encoding: UTF-8
    hikari:
#       jdbc-url: jdbc:h2:tcp://localhost:9093/mem:management_db_9093
      jdbc-url: jdbc:h2:tcp://localhost:8083/open-places
      driver-class-name: org.h2.Driver
      username: sa
      password: sa1234
  jpa:
    database-platform: H2
    show-sql: false
    hibernate:
      ddl-auto: update
  security:
    jwt:
      secret: ${'spring.security.jwt.secret':myhalf0716}
      expiration-msec: ${'spring.security.jwt.expiration-msec':86400000}
server:
  port: ${'server.port':8080}
#  address: ${'server.address':127.0.0.1}

logging:
  level:
    root: debug
    