-- DROP TABLE TBM_MEMBER;
CREATE TABLE IF NOT EXISTS tbm_member (
  memberKey bigint generated by default as identity,
  memberId varchar(80) DEFAULT NULL UNIQUE ,
  name varchar(200) DEFAULT NULL,
  email varchar(200) DEFAULT NULL,
  password varchar(200) NOT NULL,
  createdAt timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (memberKey)
) ;

-- DROP TABLE TBM_ROLE;
CREATE TABLE IF NOT EXISTS tbm_role (
  memberKey bigint,
  role varchar(20) DEFAULT 'ROLE_MEMBER',
  FOREIGN KEY(memberKey) REFERENCES tbm_member(memberKey)
);

SELECT * FROM TBM_MEMBER tm;